name: Standard CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: read

jobs:
    test:
        name: Test & Lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # Adjust based on repository language
                node-version: [18.x, 20.x, 22.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run: npm run lint
              continue-on-error: false

            - name: Run tests
              run: npm test
              env:
                  CI: true
              continue-on-error: true

    build:
        name: Build & Package
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '20.x'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build || echo "No build script available"
              continue-on-error: true

            - name: Validate package
              run: npm pack --dry-run

    notify:
        name: Notify Results
        runs-on: ubuntu-latest
        needs: [test, build]
        if: always()

        steps:
            - name: Check status
              run: |
                  echo "Test: ${{ needs.test.result }}"
                  echo "Build: ${{ needs.build.result }}"

                  if [[ "${{ needs.test.result }}" == "success" && 
                        "${{ needs.build.result }}" == "success" ]]; then
                    echo "✅ All checks passed!"
                  else
                    echo "❌ Some checks failed"
                    exit 1
                  fi
