blank_issues_enabled: false
contact_links:
    - name: 📚 Documentation
      url: https://github.com/Alteriom/repository-metadata-manager/tree/main/docs
      about: Check our comprehensive documentation for guides and examples
    - name: 💬 GitHub Discussions
      url: https://github.com/Alteriom/repository-metadata-manager/discussions
      about: Ask questions and discuss with the community
    - name: 🔒 Security Issues
      url: https://github.com/Alteriom/repository-metadata-manager/security/advisories/new
      about: Report security vulnerabilities privately
