name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        continue-on-error: false

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Run security audit
        run: npm audit --audit-level moderate
        continue-on-error: true

      - name: Test feature audits
        run: |
          node scripts/docs-compliance-check.js
          node scripts/security-audit-local.js
          node scripts/branch-protection-local.js
          node scripts/cicd-audit-local.js

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format -- --check
        continue-on-error: true

      - name: Validate package.json
        run: npm run lint:package || echo "No package lint script available"
        continue-on-error: true

      - name: Check for vulnerabilities
        run: npm audit --audit-level high
        continue-on-error: true

  build:
    name: Build & Package
    runs-on: ubuntu-latest
    needs: [test, code-quality]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build || echo "No build script available"
        continue-on-error: true

      - name: Test installation
        run: npm pack --dry-run

      - name: Validate package structure
        run: |
          echo "Checking package structure..."
          ls -la
          echo "Checking bin files..."
          ls -la bin/
          echo "Checking lib files..."
          ls -la lib/
          echo "Validating CLI executables..."
          node bin/cli.js --help
          node bin/enhanced-cli.js --help

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration || npm run test
        env:
          CI: true

      - name: Test CLI functionality
        run: |
          # Test main CLI commands
          node bin/enhanced-cli.js health --dry-run || echo "Health check completed"
          node bin/enhanced-cli.js docs --audit --dry-run || echo "Docs audit completed"
          node bin/enhanced-cli.js security --audit --dry-run || echo "Security audit completed"
          node bin/enhanced-cli.js branches --audit --dry-run || echo "Branch audit completed"
          node bin/enhanced-cli.js cicd --audit --dry-run || echo "CI/CD audit completed"

      - name: Test feature scripts
        run: |
          node scripts/test-features.js
          node scripts/setup-check.js || echo "Setup check completed"

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [test, code-quality, build, integration]
    if: always()
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check workflow status
        run: |
          echo "CI Workflow Results:"
          echo "Test job: ${{ needs.test.result }}"
          echo "Code Quality job: ${{ needs.code-quality.result }}"
          echo "Build job: ${{ needs.build.result }}"
          echo "Integration job: ${{ needs.integration.result }}"
          
          if [[ "${{ needs.test.result }}" == "success" && 
                "${{ needs.code-quality.result }}" == "success" && 
                "${{ needs.build.result }}" == "success" && 
                "${{ needs.integration.result }}" == "success" ]]; then
            echo "✅ All CI checks passed!"
          else
            echo "❌ Some CI checks failed"
            exit 1
          fi
